version: '2'

services:

  redis: 
    image: redis

  nats:
    command: -cid miniflow -mc 0 -msu 0 -DV
    image: nats-streaming:0.5.0
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
